import enum

class UserRole(str, enum.Enum):
    STUDENT = "STUDENT"
    ADMIN = "ADMIN"


class ApplicationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_AI_VERIFICATION = "UNDER_AI_VERIFICATION"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    PHYSICAL_VERIFICATION_REQUIRED = "PHYSICAL_VERIFICATION_REQUIRED"
    PHYSICAL_VERIFICATION_COMPLETED = "PHYSICAL_VERIFICATION_COMPLETED"


class DocumentType(str, enum.Enum):
    GOVERNMENT_ID = "GOVERNMENT_ID"
    MARKSHEET = "MARKSHEET"
    INCOME_CERTIFICATE = "INCOME_CERTIFICATE"
    DOMICILE_CERTIFICATE = "DOMICILE_CERTIFICATE"


class UploadStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"


class VerificationStatus(str, enum.Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"


class AppointmentStatus(str, enum.Enum):
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    RESCHEDULED = "RESCHEDULED"
