"""Add authentication fields to student and admin_officer

Revision ID: 2416706cec79
Revises: '001_initial_schema'
Create Date: 2026-09-18 17:30:49.147353

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2416706cec79'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_officers', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('GOVERNMENT_ID', 'MARKSHEET', 'INCOME_CERTIFICATE', 'DOMICILE_CERTIFICATE', name='documenttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('documents', 'upload_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='uploadstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'UPLOADED'::character varying"))
    op.alter_column('physical_verification_appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='appointmentstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEDULED'::character varying"))
    op.alter_column('scholarship_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_AI_VERIFICATION', 'NEEDS_REVIEW', 'VERIFIED', 'REJECTED', 'PHYSICAL_VERIFICATION_REQUIRED', 'PHYSICAL_VERIFICATION_COMPLETED', name='applicationstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.add_column('students', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('verification_results', 'verification_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED', name='verificationstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_results', 'verification_status',
               existing_type=sa.Enum('PENDING', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED', name='verificationstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'password_hash')
    op.alter_column('scholarship_applications', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_AI_VERIFICATION', 'NEEDS_REVIEW', 'VERIFIED', 'REJECTED', 'PHYSICAL_VERIFICATION_REQUIRED', 'PHYSICAL_VERIFICATION_COMPLETED', name='applicationstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.alter_column('physical_verification_appointments', 'status',
               existing_type=sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='appointmentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEDULED'::character varying"))
    op.alter_column('documents', 'upload_status',
               existing_type=sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='uploadstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'UPLOADED'::character varying"))
    op.alter_column('documents', 'document_type',
               existing_type=sa.Enum('GOVERNMENT_ID', 'MARKSHEET', 'INCOME_CERTIFICATE', 'DOMICILE_CERTIFICATE', name='documenttype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('admin_officers', 'password_hash')
    # ### end Alembic commands ###
